### ISSUE TITLE
raspberry-mosquito-webserver-websocket-ESP8266 

### ISSUE THREAD

**Issue by mkeyno** [chistogo/RPI-MQTT-AP#1]
sorry to open ticket to my question , but honestly I read many document across the web to find out how to make my raspberry pi as server to serve a webpage which is show status of any data came form external device , in this case I use ESP8266 deices to send data back to mosquito 1.4.11 which is  installed  on my raspberry . According to some resource , it is possible to run webserver by  mosquito itself which is set by `http_dir /usr/share/mosquitto/www` config or could bind apache with websocket & MQTT , but none of the work for me , I  really appreciated to have you tip or advice

**Comment by chistogo** [comment]
I haven't really used mosquitto as a web server. How I would approach that problem is to use the web sockets that mosquitto provides. So host your webpage using your preferred method like apache. Then create a webpage that uses a javascript MQTT client such as this one 

https://eclipse.org/paho/clients/js/

You just have to make sure that websockets are enabled on mosquito, which it is disable by default. If you used my script it is already enabled on port 9001. If you manually installed it, edit the following file.

/etc/mosquitto/mosquitto.conf

You need to add this to it

listener 1883
listener 9001
protocol websockets

Then restart mosquitto.

I have used this method for ESP8266 devices in the past and used it to create web interfaces that monitor the devices. I hope this helps. If I misunderstood you or you have any other questions please let me know.

**Comment by mkeyno** [comment]
thanks @chistogo  actually I also choose same approach and right now  websocket enabled on my mosquitto server, I intend to  create web gui on installed apache server so it shows live communication of connected devise while it bind to mySql sever to keep data , I really appreciated to share your previous effort or direct me to the link  with same approach
